name: api-build

on:
    push:
        paths:
            - "github/workflows/api-build.yml"
            - "api/**"
    workflow_dispatch: # manual

jobs:
    build:
        name: build-dotnet-api
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: dotnet --list-runtimes
            - run: dotnet --list-sdks
            - run: dotnet build
                working-directory: ./api
